apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-frontend-deployment
spec:
  selector:
    matchLabels:
      app: minecraft-server-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-server-frontend
    spec:
      containers:
        - name: minecraft-server-frontend
          image: meik99/minecraft-server-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-frontend-server-svc
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  selector:
    app: minecraft-server-frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
